title: Leutrim Pacarizi
email: Leutrim.pacarizi@tutanota.com
description: Nano Scientist & Solar Cell Researcher
baseurl: ""
url: ""
github_username: Leutrim07
linkedin_username: leutrim-pacarizi

# Build settings
theme: minima
plugins:
  - jekyll-feed
