title: Leutrim Pacarizi
email: Leutrim.pacarizi@tutanota.com
description: >- # this means to ignore newlines until "baseurl:"
  Perovskite Solar Cell Researcher
baseurl: ""
url: ""
github_username: Leutrim07
linkedin_username: leutrim-pacarizi

# Build settings
theme: minima
plugins:
  - jekyll-feed
